name: CI

on:
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production
    timeout-minutes: 15
    
    env:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan      
      run: terraform plan

